pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: GitVersion@5
  displayName: Use git version
  inputs:
    versionSpec: '5.*'
    updateAssemblyInfo: false

- task: NuGetToolInstaller@1
  displayName: Install nuget tool

- task: UseDotNet@2
  displayName: Use dotnet sdk 6.x
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: NuGetCommand@2
  displayName: Restore nuget packages
  inputs:
    restoreSolution: '$(solution)'
    
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    arguments: --no-restore  
    configuration: Release
    buildProperties: Version=$(Build.BuildNumber)
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    arguments: --no-build --no-restore          
    configuration: Release
    projects: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  displayName: Push nuget package to Nuget.Org
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget Org'