name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      BUILD_VERSION: 6.0.1.1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        preferLatestVersion: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
